version: "3.8"

services:
  telegram_bot:
    build:
      context: ./telegram_bot
    container_name: uptc_telegram_bot
    env_file:
      - ${PWD}/telegram_bot/.env
    restart: unless-stopped
    # If you want logs in compose output, remove 'detach' when running
